language: node_js
node_js:
  - "7"
before_script:
  - npm install
script:
  - npm run build
  - npm run test
after_success:
  - ./scripts/deploy.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build/
  on:
    branch: master
